### ISSUE TITLE
Subdomain support

### ISSUE THREAD

**Issue by swemixon** [kugaevsky/jquery-phoenix#17]
Thanks for a great plugin!

Does it work on subdomains as well?

I need it to work over a whole site even when the user visit pages on a subdomain.

Thanks!

**Comment by kugaevsky** [comment]
Yes, it works with subdomains.

**Comment by swemixon** [comment]
Hi Nick,

thank you for your reply.

Is there something additional I need to do to make it work with subdomains?


Med vänlig hälsning/Best regards

Michael Ljungkvist
Webbutvecklare

+46 (0) 70 67 27 937
michael@mustangmedia.se<mailto:michael@mustangmedia.se>
www.mustangmedia.se<http://www.mustangmedia.se>

[cid:E2434D42-2FE9-42EB-9CBD-9A13E85FBF24]

Mustang media AB
Parkgatan 4
264 51 Ljungbyhed
Sweden

4 feb 2015 kl. 18:23 skrev Nick Kugaevsky <notifications@github.com<mailto:notifications@github.com>>:


Yes, it works with subdomains.

**Comment by kugaevsky** [comment]
Nope. It works "out of the box". Phoenix stores each filed value with uniq key that includes domain (or subdomain) and page URL.

**Comment by swemixon** [comment]
Ok, that sounds great!

I will try to explain my example as I don’t get it to work. Maybe I’m missing something.

I have a simple test form that looks like this:

<form>
<input class="inputtest" type="text" name=”one" />
<input class="inputtest" type="text" name=”two" />
<input type="submit" name=”send" />
</form>

The class ’inputtest’ is set on the input fields and in the head section I put the code:

<script>
$(document).ready(function(){
$('.inputtest').phoenix()
});
</script>

This file is placed on both www.domain.com<http://www.domain.com> and subdomain.domain.com<http://subdomain.domain.com>.

Can I get it to work like this, that if a visitor starts filling the form out on www.domain.com<http://www.domain.com> and then click a link that directs the visitor to subdomain.domain.com<http://subdomain.domain.com> he can continue to fill the form out at the subdomain?

As of right now it seems like there is a new ’session’ or something that triggers once I click the link to the subdomain.

Thanks!



Med vänlig hälsning/Best regards

Michael Ljungkvist
Webbutvecklare

+46 (0) 70 67 27 937
michael@mustangmedia.se<mailto:michael@mustangmedia.se>
www.mustangmedia.se<http://www.mustangmedia.se>

[cid:E2434D42-2FE9-42EB-9CBD-9A13E85FBF24]

Mustang media AB
Parkgatan 4
264 51 Ljungbyhed
Sweden

4 feb 2015 kl. 22:31 skrev Nick Kugaevsky <notifications@github.com<mailto:notifications@github.com>>:


Nope. It works "out of the box". Phoenix stores each filed value with uniq key that includes domain (or subdomain) and page URL.

**Comment by kugaevsky** [comment]
No, you can't by design. There are different storage keys for forms placed on pages with different URLs.
