### ISSUE TITLE
Expire saved data

### ISSUE THREAD

**Issue by foamrider** [kugaevsky/jquery-phoenix#26]
Hi

Could there be a parameter for how long the saved data is valid, and if it is expired, removes it?

**Comment by martinschilliger** [comment]
+1

**Comment by drtomasso** [comment]
@martinschilliger seems like it hasn't been developed in some time. Meanwhile, I have added this in my PR, https://github.com/drtomasso/jquery-phoenix

**Comment by martinschilliger** [comment]
Thank you @drtomasso!
One thing I don't understand why, but when I use your code the selection of an option-tag doesn't get stored. Any idea where to look for?

**Comment by drtomasso** [comment]
Optgroup works fine by me. Could you add some code of your option-tag problem? Both html and js

**Comment by martinschilliger** [comment]
Found it out: The problem was a `<select>` which didn't had `value="foo"` set. You have to write `value="foo"`, otherways phoenix doesn't see it.
